modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Prismwork/EMIffect/issues"
license = "MIT"

[[mods]]
modId = "emiffect"
version = "${version}"
displayName = "EMIffect"
authors = "Prismwork, Flamarine"
description = '''
EMI addon that appends status effects in EMI and provides information about each status effect.
'''
logoFile = "icon.png"

[[dependencies.emiffect]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.5.21-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emiffect]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emiffect]]
modId = "emi"
type = "REQUIRED"
versionRange = "[1.0,)"
ordering = "NONE"
side = "CLIENT"